feat: add `cowboy_websocket_linger` protocol
Which is essentially `cowboy_websocket` with an important
exception: process managing the socket does not die as soon
as the socket get closed, it lingers until explicitly told
to stop through separate command or callback result.

Co-Authored-By: Feng Lee <feng@emqx.io>